commit_message: "Fix: New translations %original_file_name% from Crowdin Enterprise"
append_commit_message: false
project_id: "${{secrets.CROWDIN_PROJECT_ID}}"
api_token: "${{secrets.CROWDIN_PERSONAL_TOKEN}}"
base_path: "."
base_url: 'https://montblanc.crowdin.com'
preserve_hierarchy: true
files:
  - source: /README.md
    translation: /Translated/%two_letters_code%/%original_file_name%
