commit_message: "Fix: New translations %original_file_name% from Crowdin Enterprise"
append_commit_message: false
files:
  - source: /README.md
    translation: /Translated/%two_letters_code%/%original_file_name%
